@SETLOCAL
@ECHO OFF

SET JAR_FILE_NAME=eztweetj.jar

IF NOT EXIST %JAR_FILE_NAME% GOTO FILE_NOT_EXISTS

java -jar %JAR_FILE_NAME% %*
GOTO END

:FILE_NOT_EXISTS
ECHO %JAR_FILE_NAME%Ç™å©Ç¬Ç©ÇËÇ‹ÇπÇÒÅB
GOTO END

:END
